version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rent-your-stuff
      POSTGRES_USER : db_user
      POSTGRES_PASSWORD: db_password

    volumes:
      - ./.jmix/postgres:/var/lib/postgresql/data

